### PR TITLE
save connectivity results of USER sigdb to avoid recomputation

### PR DESCRIPTION
**Pull request by ivokwee**
This addresses issue #1052 and saves the results of the USER sigdb connectivity computation into the pgx object to avoid computation each time. 

Code should also detect if computation object should be recomputed if USER folder has new files. Please note: saving the connectivity results into the pgx will alter the original file and therefore the time stamp.

Needs latest updated playbase with modified pgx.load() and pgx.save(). They record the original filename in the pgx object as pgx$filename so the pgx can be saved to the original file location.

### CODE REVIEW

**Review by mauromiguelm — APPROVED** [review]

**Review by mauromiguelm — CHANGES_REQUESTED** [review]
at least in my computer, need_update always returns true

```r
need_update <- playbase::pgxinfo.needUpdate(
        pgxdir,
        check.sigdb = TRUE,
        verbose = FALSE
)
```

which causes re-computation when the board is re-loaded for the same dataset

```r
Browse[1]> need_update
[1] TRUE
Browse[1]> !file.exists(sigdb.file)
[1] FALSE
Browse[1]> need_update || !file.exists(sigdb.file)
[1] TRUE
```

**Comment by ivokwee** [comment]
What do you mean with "invalid pgx", some slots missing because of incomplete calculation?

**Comment by ivokwee** [comment]
Mine 'needUpdate' give false but I think all my pgx are 'valid'
image

**Comment by mauromiguelm** [comment]
> What do you mean with "invalid pgx", some slots missing because of incomplete calculation?

the ones that do not pass https://github.com/bigomics/playbase/blob/f8acc95e6b1374d21ad3d9ad45ee76e386450d03/R/pgx-init.R#L48-L54
We could have a check before incorporating pgx into datasetInfo folder, so the ones not passing tests above will not be included and not trigger recomputation.. but thats an edge case probably

**Comment by ivokwee** [comment]
OK. merging. Invalid PGX should not happen. this is a separate problem.

**Pull request merged**
