### PR TITLE
Fix #632 custom name plots

### LINKED ISSUE #632: Add custom name to the plots when downloaded
When plots or data is downloaded using the download button, they have the same name. 
E.g.: 'plot.png'  when png files are downloaded. 
It would be nice to have custom names to the plots or data.
E.g.:  expression_plot_top_genes.png when expression plot is downloaded. 
  

  
  
  
<details> <summary><strong>Session Info</strong></summary>

```r
```
</details>

### PR DESCRIPTION
**Pull request by ShaliniPandurangan**
## Description

The plots now have custom name when downloaded.

### CODE REVIEW

**Comment by ivokwee** [comment]
Just please make sure the .png and .pdf are properly appended to the name

**Review by mauromiguelm — CHANGES_REQUESTED** [review]
changes need to be applied to the table module as well!

**Comment by ShaliniPandurangan** [comment]
> Here are examples of the titles of some plots -- is it possible to remove the last two dashes and associated words? They're a bit uninformative. So, remove the "-plot-title" and "-plotmodule-title" and such -- it's not always the same two words though FYI.
> 
> Screen Shot 2023-08-22 at 5 28 35 PM

I removed the uninformative information. I checked all the other uninformative words as well. Thanks for the tip. 



> Just please make sure the .png and .pdf are properly appended to the name

I made sure they have proper extension. @ncullen93 was printing just the filenames with out extension.

> changes need to be applied to the table module as well!
I added the changes to the table module as well.

**Comment by ShaliniPandurangan** [comment]
> Here are examples of the titles of some plots -- is it possible to remove the last two dashes and associated words? They're a bit uninformative. So, remove the "-plot-title" and "-plotmodule-title" and such -- it's not always the same two words though FYI.
> 
> Screen Shot 2023-08-22 at 5 28 35 PM

I removed the uninformative information. I checked all the other uninformative words as well. Thanks for the tip. 



> Just please make sure the .png and .pdf are properly appended to the name

I made sure they have proper extension. Screenshot from @ncullen93 is just the filenames without extension. 

> changes need to be applied to the table module as well!

I added the changes to the table module as well.

**Pull request closed without merging**
