### PR TITLE
Implementation BioMart and 214 organisms in OmicsPlayground

### PR DESCRIPTION
**Pull request by mauromiguelm**
## Description

- Create the minimal UI so that users can select the species among 214 organisms
- Fix server side code to allow compatility with new species IDs (eg. remove uppercase)
- Use human ortholog as common denominator in several boards (genesets, compare datasets...)

## PGX
The pgx object was changed. The major changes are:
- pgx$organisms is now defined by the user, and not guessing by looking at probe IDs
- pgx$version is matched to playbase package version (it moves 0.01 every time we submit a PR)
- pgx$GMT is converter to species symbol based on human orthologs
- convert to hugo is now used to collapse by gene or not. (more on this later)
- pgx$genes was refactored to allow transcript or feature-level analysis, and match to gene symbol where possible.

## pgx$genes
- has three new columns: symbol, feature and human_ortholog
- when collapse by gene, rownames, gene_name and symbol equals to Gene symbol.
- when NOT collapsed by gene, rownames will be features, gene_names will be features, and symbol will be Gene symbol, when possible. This will allow transcript-level analysis in the future.

## Probe types covered per species 

[probes_per_species.csv](https://github.com/bigomics/omicsplayground/files/13225312/probes_per_species.csv)

## Test Deployment
This is branch is deployed on [test.playground.bigomics.ch](url)

## Playbase branch and PR
This PR is linked to playbase PR https://github.com/bigomics/playbase/pull/61

## To-do list
- review code and pgx so we get the same results from master branch
- test that BioMart works well in deployment (it seems it does)
- test as many old pgx as possible, to make sure they are back-compatible. They should be at this stage.

## Acknowledgements
Huge thanks to Santiago @phisanti for making it possible!

### CODE REVIEW

**Comment by mauromiguelm** [comment]
@phisanti 
running on local docker, we have some network error with biomart:
image

**Comment by mauromiguelm** [comment]
boards with error when loading a glioblastoma public dataset

image

image

**Comment by phisanti** [comment]
> boards with error when loading a glioblastoma public dataset
> 
> image
> 
> image

Error in image 1 is now solved. 
Error in image 2 has been found also in master. Solution in progress with the help of @ESCRI11

**Comment by phisanti** [comment]
Error 2 has been resolved in #735

**Comment by ESCRI11** [comment]
#732 is solved

**Pull request merged**
