### PR TITLE
Fix #457: increase box size to allow contrast name visibility

### LINKED ISSUE #457: upload module > contrasts: increase box size to allow contrast name visibility
image

### PR DESCRIPTION
**Pull request by ESCRI11**
This closes #457 

## Description
Did three things

- Added breathing space to the column itself
- Moved more pieces to `bslib`
- Used `textAreaInput` for multiple line input

@mauromiguelm Let me know if the dimensions and usability are what you expected, if not I will increase/decrease them.

### CODE REVIEW

**Comment by mauromiguelm** [comment]
Hi Xavier,

I did some chances to the UI with suggestions from Ivo, removed unnecessary elements, with some feedback from Ivo. The idea is to avoid crumping of too many elements in a single row, and optimize space. What do you think?

What would be missing:
1. Ivo would like the old text input and not text area, as the problem with long contrast names should be fixed now.
2. The drop down is not working, maybe we should add `overflow-y: auto` in the phenotype selector.
3. General styling

**Comment by ESCRI11** [comment]
@mauromiguelm How does this look?

image

image

image

**Comment by mauromiguelm** [comment]
maybe missing the button to add contrasts?

**Comment by ESCRI11** [comment]
Let me know if you like the button placement

**Comment by mauromiguelm** [comment]
finished, for me we can merge

**Comment by mauromiguelm** [comment]
wait I have one strange conflict

**Comment by mauromiguelm** [comment]
to keep consistency with other pages, we need cards inside layout col wrap to keep page to 100%

sorry for the formatting, I had git issues and lost a big commit somewhere

**Review by mauromiguelm — APPROVED** [review]

**Pull request merged**
