### PR TITLE
Genesets update

### PR DESCRIPTION
**Pull request by mauromiguelm**
**CAUTION:** this has to be tested with `dev-gmt` branches on `playbase` and `playdata`

playbase PR: https://github.com/bigomics/playbase/pull/10
playdata PR: https://github.com/bigomics/playdata/pull/3

**Improvements:**

- global genesets updated, many new databases included.
- wikipathways genesets updated and forced into results.
- improved reproducibility, as all genesets are created by scripts.
- improved transparency, as databases are listed in `playdata::GSET_INFO`.
- giving the extensive testing, I simplified pgx creation with example data. See README file.
- pgx that are created after this PR will include key geneset statistics, the most important being the original geneset size, and the number of genes present in the original geneset (See `playdata::GSET_SIZE`) . These metrics are now shown in enrichment board.
- all boards will works with both legacy and newly generated pgx.
- scripts used to generate human genesets can be easily adapted for more exotic species. With minor changes in the scripts, we can have genesets for many new species.
- Given the results from the statistical methods, I opted to be on the safe side and included genesets covering 15 to 400 genes. Since most genesets are not covered 1:1 by genes in dataset, genesets of 400 genes often have 100-200 genes. We should be safe w.r.t. q-values inflation due to large genesets.
- For the enrichment table DB URLs, I covered most databases, the remaining are more difficult to implement either by not having an easy url query or by not having standards genesets naming.

**Possible future improvements:**

- Since we are updating pgx compute, this PR could be an oportunity to move more code from `enrichment_server.R` to `playbase::pgx.compute`. We need to better align this given old pgx will not have that element. See https://github.com/bigomics/omicsplayground/blob/dev-gmt/components/board.enrichment/R/enrichment_server.R#L208-L255
- filter out gene sets with very low number of genes. See results and let me know, but sometimes we have 20 genes covered in genesets with 300 genes.
- improve column names in enrichment table (what is AveExpr0, stars, meta.q, etc...). The user should easily know what these metrics are, or they should be removed from the table.
- change reactome pathway color to blue and red, matching tables

**To discuss before merge:**
- benchmark results with Axel, maybe update default statistics for genesets.
- legal team: To avoid copyright issues, ELSEVIER and Biocarta were removed. ELSEVIER looks nice, I recommend investigating the possibility to include it, as they sometimes say its "free". For KEGG, we could more actively remove, for example not showing results in geneset enrichment from old pgx that included kegg. For now, I removed the url to kegg website.

### CODE REVIEW

**Comment by ivokwee** [comment]
Please finish the remaining "to-do before merge". Just the URL fix is fine. Axel/user feedback can be done later. The custom gene set is already separate issue #93.

**Comment by mauromiguelm** [comment]
@ivokwee done, I made many improvements in many parts of the script and uploaded two new pgx datasets for testing in the shared folder.

Tomorrow I want to deploy the docker for testing, wish me luck!

**Comment by ivokwee** [comment]
Please do not put unnecessary extra Pgx  in the repo. The repo should be as light as possible.

**Comment by mauromiguelm** [comment]
> Please do not put unnecessary extra Pgx in the repo. The repo should be as light as possible.

Hi Ivo,

I did not upload any pgx; all datasets for testing are in our google drive. These datasets can be accessed through the shared folders in google drive, or through the email I sent a few days ago with more details.

Best,
M

**Pull request merged**
