### PR TITLE
change getPgxDir() for auth$options$user_dir

### PR DESCRIPTION
**Pull request by phisanti**
This is a simple fix to issue #573. I just changed 5 lines of code in `board.connectivity/R/connectivity_server.R`. The lines are 95, 110, 115, and 195.

### CODE REVIEW

**Comment by ivokwee** [comment]
I get an error 'auth not found'. Did you test your code after your fix???  Please after every modification and before PR you *have* to test your code. If possible describe and post a screenshot to document the fix worked.
 
image

**Comment by phisanti** [comment]
I got it (see image). I think it was a problem on the description of the issue. I changed the `auth$options$user_dir` for `auth$user_dir`.

image

**Comment by ivokwee** [comment]
Does it work now? Please run and check carefully before review or merge request.

**Comment by ivokwee** [comment]
OK. seems fine. I will merge.

**Pull request merged**
