### PR TITLE
feat: probe filter defaults for proteomics

### PR DESCRIPTION
**Pull request by ESCRI11**
## Description
All probe filter are set as disabled by default for proteomics data.

image

### CODE REVIEW

**Comment by ivokwee** [comment]
Can we see if it is possible to have user/deployment defined defaults in a file like an DEFAULTS or defaults.yaml file? In that case we can set for any deployment different setting. No need to do it on User level, just Deployment level like the current global OPTIONS file.

**Comment by ESCRI11** [comment]
@ivokwee Sounds like a good idea, working on it

**Comment by ESCRI11** [comment]
@ivokwee Check the last 2 commits for the first iteration of your idea. If looks good to you I can extend it to different defaults. Let me know

**Comment by ivokwee** [comment]
Nice. But I took out the datatype dependency (if proteomics). I think this is more a client preference. and to keep it simple. perhaps in the future we need it but I want to keep any datatype switches at a minimum.

**Comment by ivokwee** [comment]
We can extend this to many other places if needed. Not sure if something "automatic" by writing to Shiny's input could be done. For now this is minimal and good.

**Comment by ivokwee** [comment]
Rembmer. For MPOC we need to modify the DEFAULTS file at deployment.

**Pull request merged**
